Repository konveyor/tackle2-hub, pull requests merged in 2023-06, with the labels that each got.

#364 :bug: Addon fact put
  addon/application.go
  api/application.go
  hack/update/fact.sh
Labels: NEEDS BACKPORT

#369 :bug: Discard not-found error when reaping tasks.
  task/manager.go
Labels: NEEDS BACKPORT

#359 :sparkles: Omit Ref empty Name in API
  api/base.go
Labels: BACKPORT-0.2

#363 Fix Pathfinder assessment counting
  api/pathfinder.go
Labels: BACKPORT-0.2

#380 :book: Add API documentation for metrics endpoint
  api/metric.go
  cmd/main.go
  docs/binding.txt
  docs/docs.go
  docs/index.html
  docs/swagger.json
  docs/swagger.yaml
Labels: BACKPORT-0.2

#375 :seedling: add dependency package in test/api
  api/dependency.go
  binding/dependency.go
  binding/richclient.go
  test/api/dependency/api_test.go
  test/api/dependency/pkg.go
  test/api/dependency/samples.go
Labels: test/api

#387 :seedling: add cross dependency test
  docs/test-api-matrix.md
  test/api/dependency/api_test.go
  test/api/dependency/samples.go
Labels: test/api

#376 :sparkles: Seeds: Missing space in description
  migration/v3/seed/main.go
  migration/v4/migrate.go
Labels: BACKPORT-0.2

#404 Add unique index on Wave name/start/end
  migration/v5/model/migrationwave.go
Labels: BACKPORT-0.2
